Traceback (most recent call last):
  File "/home/moiseszm/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 622, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/home/moiseszm/miniconda3/lib/python3.8/site-packages/nbclient/util.py", line 85, in ensure_async
    result = await obj
  File "/home/moiseszm/miniconda3/lib/python3.8/site-packages/jupyter_client/asynchronous/channels.py", line 48, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/moiseszm/miniconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/moiseszm/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/moiseszm/miniconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/moiseszm/miniconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/moiseszm/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/moiseszm/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/moiseszm/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 841, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/home/moiseszm/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 646, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "/home/moiseszm/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 696, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
%%time
YLOne23 = speedup_array(ALOneTot23,m6np)
#YLOne32 = speedup_array(ALOneTot32,m6np)

YLOne13 = speedup_array(ALOneTot13,m6np)
#YLOne31 = speedup_array(ALOneTot31,m6np)

YLOne12 = speedup_array(ALOneTot12,m6np)
#YLOne21 = speedup_array(ALOneTot21,m6np)
-------------------

