Traceback (most recent call last):
  File "/home/moiseszm/miniconda3/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/home/moiseszm/miniconda3/lib/python3.7/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/moiseszm/miniconda3/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/moiseszm/miniconda3/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/moiseszm/miniconda3/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/home/moiseszm/miniconda3/lib/python3.7/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/home/moiseszm/miniconda3/lib/python3.7/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/moiseszm/miniconda3/lib/python3.7/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
hGdGu = lfvhd.VertexHSS(-I*Î»1*v)
GuljÎ½l = lfvhd.VertexSFF(I*(sqrt(2)/v)*mj*U[l,j],0)
GdliÎ½l = lfvhd.VertexSFF(0,I*(sqrt(2)/v)*mi*conjugate(U[l,i]))

hGdWu = lfvhd.VertexHSpVm(-I*g/2)
WuljÎ½l = lfvhd.VertexVFF(0,-I*(g/sqrt(2))*U[l,j])
hWdGu = lfvhd.VertexHVpSm(-I*g/2)
WdliÎ½l = lfvhd.VertexVFF(0,-I*(g/sqrt(2))*conjugate(U[l,i]))
hWdWu = lfvhd.VertexHVV(I*g**2/2*v)
hljlj = lfvhd.VertexHFF((I*g*mj)/(2*sqrt(2)*mW))
hlili = lfvhd.VertexHFF((I*g*mi)/(2*sqrt(2)*mW))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-7-991ae2bf881c>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mhGdGu[0m [0;34m=[0m [0mlfvhd[0m[0;34m.[0m[0mVertexHSS[0m[0;34m([0m[0;34m-[0m[0mI[0m[0;34m*[0m[0mÎ»1[0m[0;34m*[0m[0mv[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mGuljÎ½l[0m [0;34m=[0m [0mlfvhd[0m[0;34m.[0m[0mVertexSFF[0m[0;34m([0m[0mI[0m[0;34m*[0m[0;34m([0m[0msqrt[0m[0;34m([0m[0;36m2[0m[0;34m)[0m[0;34m/[0m[0mv[0m[0;34m)[0m[0;34m*[0m[0mmj[0m[0;34m*[0m[0mU[0m[0;34m[[0m[0ml[0m[0;34m,[0m[0mj[0m[0;34m][0m[0;34m,[0m[0;36m0[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0mGdliÎ½l[0m [0;34m=[0m [0mlfvhd[0m[0;34m.[0m[0mVertexSFF[0m[0;34m([0m[0;36m0[0m[0;34m,[0m[0mI[0m[0;34m*[0m[0;34m([0m[0msqrt[0m[0;34m([0m[0;36m2[0m[0;34m)[0m[0;34m/[0m[0mv[0m[0;34m)[0m[0;34m*[0m[0mmi[0m[0;34m*[0m[0mconjugate[0m[0;34m([0m[0mU[0m[0;34m[[0m[0ml[0m[0;34m,[0m[0mi[0m[0;34m][0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;34m[0m[0m
[1;32m      5[0m [0mhGdWu[0m [0;34m=[0m [0mlfvhd[0m[0;34m.[0m[0mVertexHSpVm[0m[0;34m([0m[0;34m-[0m[0mI[0m[0;34m*[0m[0mg[0m[0;34m/[0m[0;36m2[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'Î»1' is not defined
NameError: name 'Î»1' is not defined

